{
  "hash": "e1ab6ed894bbe679be98a97193095064",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Difference Scores: Simple Regression\"\nauthor: \"Biostatistics Working Group\"\ntheme: cosmo\n---\n\n\n# Simple Regression {.unnumbered}\n\n## Overview\n\n<p>\n\nThis example assesses whether growth in a subsample of ABCD participants from Baseline (T0) to the 1-Year follow-up (T1) differs significantly based on handedness, using height (\"anthroheightcalc\") as a representative metric of growth. The analysis is conducted in two primary steps: 1) a difference score is calculated between baseline and Year_1 height measurements for each participant; 2) a simple regression analysis is used to test whether sex (boy, girl) predicts the average difference value in participants height from baseline to the 1-Year follow-up. Finally, a visual inspection is further conducted via a violin plot to graphically represent the relationship between difference scores and sex. The ensuing analysis and interpretations are detailed in the subsequent sections.\n\n</p>\n\n## Preliminary Setup\n\n::: panel-tabset\n### Install Packages {.tabset .tabset-fade .tabset-pills}\n\n::: blue\n> **This code installs the r packages necessary for this example, if\n> they are not already installed**\n\n\n::: {.cell messages='false'}\n\n```{.r .cell-code}\n# rm(list = ls())\n\n# Create a list of required packages\npackages_required <- c(\"tidyverse\",\"easystats\",\"lme4\",\"gtsummary\",\"report\",\"broom\",\"gridExtra\")\n\n# Check which packages are not installed and install them\npackages_to_install <- setdiff(packages_required, rownames(installed.packages()))\nif (length(packages_to_install) > 0) {\n    install.packages(packages_to_install)\n}\n\n# Load the required packages\nlapply(packages_required, library, character.only = TRUE)\n```\n:::\n\n:::\n\n### Load Packages\n\n::: blue\n**This code loads the r libraries necessary for this example**\n\n\n::: {.cell messages='false'}\n\n```{.r .cell-code}\nlibrary(tidyverse)    # Collection of R packages for data science\nlibrary(easystats)    # Collection of R packages statistical modeling, visualization, and reporting\nlibrary(rstatix)      # Pipe-friendly framework for performing common stats\nlibrary(gtsummary)    # Publication-ready tables\nlibrary(report)       # Easy reporting of regression analyses\nlibrary(broom)        # Tidy and augment statistical models output\nlibrary(gridExtra)    # Arrange multiple grid-based plots on a page\n```\n:::\n\n:::\n\n### Config Options\n\n::: blue\n**This code configures knitr code chunk options**\n\n\n::: {.cell messages='false'}\n\n```{.r .cell-code}\nknitr::opts_chunk$set(echo = T, message=F, warning=F, error=F, \n                      comment=NA, cache=T, code_folding=T,\n                      R.options=list(width=220, digits = 3),\n                      fig.align='center', \n                      out.width='75%', fig.asp=.75)\n```\n:::\n\n:::\n:::\n\n## Descriptives Overview\n\n::: panel-tabset\n### Read and View Data {.tabset .tabset-fade .tabset-pills}\n\n::: blue\n**This code reads in and shows the data to be used in the current\nexample**\n\n\n::: {.cell layout-align=\"center\" messages='false'}\n\n```{.r .cell-code}\n# Set the data paths\ndata_path_1 <- \"/Users/shawes/ABCD/data/rds/abcd_5.0_rds/demo5.0.rds\"\ndata_path_2 <- \"/Users/shawes/ABCD/data/rds/abcd_5.0_rds/core-rds-5.0/non-imaging_excluding_nt_5.0.rds\"\n\n# Read the data\ndata_demographics <- readRDS(data_path_1)\ndata_nonimaging <- readRDS(data_path_2)\n\n# Subset the nonimaging data to include desired variables\nselected_vars <- c(\"src_subject_id\", \"eventname\", \"nihtbx_totalcomp_fc\", \"anthroweightcalc\", \"anthroheightcalc\")\nsubset_data <- data_nonimaging[, selected_vars]\n\nlibrary(dplyr)\n# # Merge the datasets on 'src_subject_id' and 'eventname'\nmerged_data <- data_demographics %>%\n  full_join(subset_data, by = c(\"src_subject_id\", \"eventname\"))\n\n# Inspect the merged data structure\nstr(merged_data)\n\n# Define event names to be retained in the analysis and convert variables to appropriate data types\neventnames_to_include <- c(\"baseline_year_1_arm_1\",\n                           \"1_year_follow_up_y_arm_1\",\n                           \"2_year_follow_up_y_arm_1\",\n                           \"3_year_follow_up_y_arm_1\",\n                           \"4_year_follow_up_y_arm_1\")\n\ndf <- merged_data %>%\n  filter(eventname %in% eventnames_to_include) %>%\n  mutate(\n    src_subject_id = as.factor(src_subject_id),\n    eventname = factor(eventname, levels = eventnames_to_include, ordered = TRUE),\n    age = as.numeric(age),\n    sex = as.factor(sex),\n    race.4level = as.factor(race.4level),\n    hisp = as.factor(hisp),\n    high.educ.bl = as.factor(high.educ.bl),\n    household.income.bl = as.factor(household.income.bl),\n    acs_raked_propensity_score = as.numeric(acs_raked_propensity_score),\n    rel_family_id.bl = as.factor(rel_family_id.bl),\n    site_id_l = as.factor(site_id_l),\n    nihtbx_totalcomp_fc = as.numeric(nihtbx_totalcomp_fc),\n    anthroweightcalc = as.numeric(anthroweightcalc),\n    anthroheightcalc = as.numeric(anthroheightcalc)\n  ) %>%\n  # Exclude cases from unused assessment waves\n  filter(!is.na(eventname))\n```\n:::\n\n:::\n\n### Descriptives\n\n::: blue\n**This code creates a descriptives table**\n\n\n::: {.cell layout-align=\"center\" messages='false'}\n\n```{.r .cell-code}\ndescriptives_table <- df %>%\n  select(eventname, sex, race.4level, hisp, anthroweightcalc) %>%\n  mutate(eventname = factor(eventname, labels = c(\"Baseline\", \"Year 1\",\"Year 2\",\"Year 3\",\"Year 4\"))) %>%\n  mutate(sex = factor(sex, labels = c(\"Female\", \"Male\"))) %>%\n  tbl_summary(\n    by = eventname,\n    missing = \"no\",\n    label = list(sex ~ \"Sex\", race.4level ~ \"Race\", hisp ~ \"Hispanic\", \n                 anthroweightcalc ~ \"Weight\"),\n    statistic = list(all_continuous() ~ \"{mean} ({sd}) )\", all_categorical() ~ \"{p}%\"),\n  ) %>%\nmodify_header(all_stat_cols() ~ \"**{level}**<br>N = {n}\") %>%\n  bold_labels() %>%\n  italicize_levels() %>%\n  modify_spanning_header(all_stat_cols() ~ \"**Assessment Wave**\")\ntheme_gtsummary_compact()\n\ndescriptives_table\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"yzbraoipto\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#yzbraoipto table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#yzbraoipto thead, #yzbraoipto tbody, #yzbraoipto tfoot, #yzbraoipto tr, #yzbraoipto td, #yzbraoipto th {\n  border-style: none;\n}\n\n#yzbraoipto p {\n  margin: 0;\n  padding: 0;\n}\n\n#yzbraoipto .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 13px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#yzbraoipto .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#yzbraoipto .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#yzbraoipto .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#yzbraoipto .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#yzbraoipto .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yzbraoipto .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#yzbraoipto .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#yzbraoipto .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#yzbraoipto .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#yzbraoipto .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#yzbraoipto .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#yzbraoipto .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#yzbraoipto .gt_group_heading {\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#yzbraoipto .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#yzbraoipto .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#yzbraoipto .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#yzbraoipto .gt_row {\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#yzbraoipto .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yzbraoipto .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#yzbraoipto .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#yzbraoipto .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#yzbraoipto .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yzbraoipto .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#yzbraoipto .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#yzbraoipto .gt_last_summary_row {\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yzbraoipto .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yzbraoipto .gt_first_grand_summary_row {\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#yzbraoipto .gt_last_grand_summary_row_top {\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yzbraoipto .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#yzbraoipto .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yzbraoipto .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#yzbraoipto .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yzbraoipto .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#yzbraoipto .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yzbraoipto .gt_left {\n  text-align: left;\n}\n\n#yzbraoipto .gt_center {\n  text-align: center;\n}\n\n#yzbraoipto .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#yzbraoipto .gt_font_normal {\n  font-weight: normal;\n}\n\n#yzbraoipto .gt_font_bold {\n  font-weight: bold;\n}\n\n#yzbraoipto .gt_font_italic {\n  font-style: italic;\n}\n\n#yzbraoipto .gt_super {\n  font-size: 65%;\n}\n\n#yzbraoipto .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#yzbraoipto .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#yzbraoipto .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#yzbraoipto .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#yzbraoipto .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#yzbraoipto .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#yzbraoipto .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Characteristic&lt;/strong&gt;\"><strong>Characteristic</strong></th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"5\" scope=\"colgroup\" id=\"&lt;strong&gt;Assessment Wave&lt;/strong&gt;\">\n        <span class=\"gt_column_spanner\"><strong>Assessment Wave</strong></span>\n      </th>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Baseline&lt;/strong&gt;&lt;br&gt;N = 11868&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>Baseline</strong><br>N = 11868<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Year 1&lt;/strong&gt;&lt;br&gt;N = 11220&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>Year 1</strong><br>N = 11220<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Year 2&lt;/strong&gt;&lt;br&gt;N = 10973&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>Year 2</strong><br>N = 10973<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Year 3&lt;/strong&gt;&lt;br&gt;N = 10336&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>Year 3</strong><br>N = 10336<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Year 4&lt;/strong&gt;&lt;br&gt;N = 4754&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>Year 4</strong><br>N = 4754<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Sex</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"></td>\n<td headers=\"stat_3\" class=\"gt_row gt_center\"></td>\n<td headers=\"stat_4\" class=\"gt_row gt_center\"></td>\n<td headers=\"stat_5\" class=\"gt_row gt_center\"></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-style: italic;\">    Female</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">48%</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">48%</td>\n<td headers=\"stat_3\" class=\"gt_row gt_center\">48%</td>\n<td headers=\"stat_4\" class=\"gt_row gt_center\">47%</td>\n<td headers=\"stat_5\" class=\"gt_row gt_center\">48%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-style: italic;\">    Male</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">52%</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">52%</td>\n<td headers=\"stat_3\" class=\"gt_row gt_center\">52%</td>\n<td headers=\"stat_4\" class=\"gt_row gt_center\">53%</td>\n<td headers=\"stat_5\" class=\"gt_row gt_center\">52%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Race</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"></td>\n<td headers=\"stat_3\" class=\"gt_row gt_center\"></td>\n<td headers=\"stat_4\" class=\"gt_row gt_center\"></td>\n<td headers=\"stat_5\" class=\"gt_row gt_center\"></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-style: italic;\">    Asian</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">0.5%</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">0.4%</td>\n<td headers=\"stat_3\" class=\"gt_row gt_center\">0.4%</td>\n<td headers=\"stat_4\" class=\"gt_row gt_center\">0.5%</td>\n<td headers=\"stat_5\" class=\"gt_row gt_center\">0.4%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-style: italic;\">    Black</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">16%</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">15%</td>\n<td headers=\"stat_3\" class=\"gt_row gt_center\">15%</td>\n<td headers=\"stat_4\" class=\"gt_row gt_center\">14%</td>\n<td headers=\"stat_5\" class=\"gt_row gt_center\">12%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-style: italic;\">    Other/Mixed</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">17%</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">17%</td>\n<td headers=\"stat_3\" class=\"gt_row gt_center\">17%</td>\n<td headers=\"stat_4\" class=\"gt_row gt_center\">17%</td>\n<td headers=\"stat_5\" class=\"gt_row gt_center\">16%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-style: italic;\">    White</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">66%</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">67%</td>\n<td headers=\"stat_3\" class=\"gt_row gt_center\">67%</td>\n<td headers=\"stat_4\" class=\"gt_row gt_center\">68%</td>\n<td headers=\"stat_5\" class=\"gt_row gt_center\">72%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Hispanic</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">21%</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">20%</td>\n<td headers=\"stat_3\" class=\"gt_row gt_center\">20%</td>\n<td headers=\"stat_4\" class=\"gt_row gt_center\">20%</td>\n<td headers=\"stat_5\" class=\"gt_row gt_center\">21%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Weight</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">83 (24) )</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">94 (28) )</td>\n<td headers=\"stat_3\" class=\"gt_row gt_center\">109 (49) )</td>\n<td headers=\"stat_4\" class=\"gt_row gt_center\">123 (38) )</td>\n<td headers=\"stat_5\" class=\"gt_row gt_center\">139 (111) )</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"6\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span> %; Mean (SD) )</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n:::\n:::\n\n## Results\n\n::: panel-tabset\n### Build Model: Step 1 {.tabset .tabset-fade .tabset-pills}\n\n::: blue\nThe code snippet below tells R to compute a difference score by subtracting each participant’s height at T1 from their height at T0. Relevant summary statistics are also provided.\n\n**STEP 1: Compute Difference Score**\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .fold-hide .cell-code}\n# Define the function to compute difference scores for a given variable and provide a summary\n# Function to compute difference scores for a given variable and provide a summary\ncompute_difference_and_summary <- function(df, variable_name) {\n    # Define the event names of interest\n    baseline_event <- \"baseline_year_1_arm_1\"\n    followup_event <- \"1_year_follow_up_y_arm_1\"\n\n    # Compute the difference between Baseline and Year 1 data for the given variable\n    diff_data <- df %>%\n        filter(eventname %in% c(baseline_event, followup_event)) %>% # Filter for specific event names\n        select(src_subject_id, eventname, all_of(variable_name)) %>% # Select required columns\n        spread(eventname, variable_name) %>% # Convert data from long to wide format\n        mutate(diff = get(followup_event) - get(baseline_event)) %>% # Compute difference between the two time points\n        drop_na(diff) # Exclude rows with NA in the computed difference\n\n    # Summarize the computed difference scores\n    diff_summary <- summary(diff_data$diff)\n\n    # Return the difference data and its summary\n    list(data = diff_data, summary = diff_summary)\n}\n\n# List of variables for which difference scores are to be computed\nvariables_of_interest <- c(\"anthroheightcalc\")\n\n# Compute and store difference scores and summaries for each variable in a list\ndifference_and_summary_list <- lapply(variables_of_interest, function(var) {\n    compute_difference_and_summary(df, var)\n})\n\n# Extract the difference data for the 'anthroheightcalc' variable\nheight_diff_data <- difference_and_summary_list[[1]]$data\n\n# Merge the 'diff' column back to the main df using 'src_subject_id' as the key\ndf <- left_join(df, height_diff_data %>% select(src_subject_id, diff), by = \"src_subject_id\")\n```\n:::\n\n\n**Descriptive Statistics for the Difference Score**\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Compute statistical summaries for the difference score variable\nlapply(difference_and_summary_list, function(item) {\n    print(item$summary)\n})\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  -51.9     1.8     2.2     2.4     3.0    67.0 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1]]\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  -51.9     1.8     2.2     2.4     3.0    67.0 \n```\n\n\n:::\n:::\n\n\nThis summary of the difference score variable indicates that the differences range from a decrease of -51.875 units to an increase of 67 units. The median difference is 2.25 units, and the average difference is approximately 2.3660611 units. There are 0 missing values in this difference score dataset.\n\n**Descriptive Statistics for the Height Variable**\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n## Summary statistics\n# Compute summary statistics for Height by eventname\nsummary <- df %>%\n    group_by(eventname) %>%\n    get_summary_stats(anthroheightcalc, type = \"mean_sd\")\n\ndata.frame(summary)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"eventname\"],\"name\":[1],\"type\":[\"ord\"],\"align\":[\"right\"]},{\"label\":[\"variable\"],\"name\":[2],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"n\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"mean\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"sd\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"baseline_year_1_arm_1\",\"2\":\"anthroheightcalc\",\"3\":\"11859\",\"4\":\"55.2\",\"5\":\"3.33\"},{\"1\":\"1_year_follow_up_y_arm_1\",\"2\":\"anthroheightcalc\",\"3\":\"11142\",\"4\":\"57.6\",\"5\":\"3.65\"},{\"1\":\"2_year_follow_up_y_arm_1\",\"2\":\"anthroheightcalc\",\"3\":\"9190\",\"4\":\"60.2\",\"5\":\"3.61\"},{\"1\":\"3_year_follow_up_y_arm_1\",\"2\":\"anthroheightcalc\",\"3\":\"3797\",\"4\":\"62.4\",\"5\":\"4.10\"},{\"1\":\"4_year_follow_up_y_arm_1\",\"2\":\"anthroheightcalc\",\"3\":\"4184\",\"4\":\"64.7\",\"5\":\"4.81\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nThe summary statistics provide insights into the Height variable across different `eventname` categories. At baseline, the average height is approximately 55.241 units with a standard deviation of 3.331. Over the years, there’s a noticeable increase in average height: by the first year, it’s about 57.595 units, and it continues to rise, reaching approximately 64.694 units by the fourth year. The standard deviation remains relatively consistent over the years, suggesting similar variability in height measurements across these time points.\n\n:::\n\n### Build Model: Step 2 {.tabset .tabset-fade .tabset-pills}\n\n::: blue\nA simple regression analyses is conducted to examine whether a grouping variable (sex) significantly predicts the difference score value (indicating significant group differences in the average difference score).\n\n**STEP 2: Conduct regression on Difference Score**\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .fold-hide .cell-code}\n# Merge the 'sex' variable from the original dataframe 'df' to 'height_diff_data'\nmerged_data <- height_diff_data %>%\n  left_join(df %>% select(src_subject_id, sex), by = \"src_subject_id\")\n\n# Ensure 'sex' is a factor\nmerged_data$sex <- as.factor(merged_data$sex)\n\n# Run the regression\nmodel <- lm(diff ~ sex, data = merged_data)\n\n# Get the summary of the regression model\nmodel_summary <- summary(model)\n\nmodel_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = diff ~ sex, data = merged_data)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-54.41  -0.59  -0.11   0.47  64.47 \n\nCoefficients:\n                 Estimate Std. Error t value Pr(>|t|)    \n(Intercept)        2.5308     0.0167   151.8   <2e-16 ***\nsexMale or other  -0.3376     0.0230   -14.7   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2.51 on 47586 degrees of freedom\nMultiple R-squared:  0.00449,\tAdjusted R-squared:  0.00447 \nF-statistic:  215 on 1 and 47586 DF,  p-value: <2e-16\n```\n\n\n:::\n:::\n\n\nThis regression analysis evaluates whether sex (boy, girl) predicts the average difference in participants' height from baseline to the 1-Year follow-up. The output from our model provides: \n\ni. an F-statistic of 214.6560227; \nii. degrees of freedom of 47586; \niii. a parameter estimate of -0.3376126; \niv. standard error of 0.0230434; \nv. p-value of 1.6900378\\times 10^{-48}. \n\nCompared to boys (the reference group), girls have an average increase in height difference of approximately -0.338 units. This effect was marginally significant with a p-value of 0. Overall, the model explained a very small portion of the variance in height difference, with an adjusted R-squared value of 0.00447, and the overall model significance was not statistically significant with a p-value of 1.6900378\\times 10^{-48}.\n\n:::\n\n### Model Plots\n\n::: blue\n\n::: {.cell layout-align=\"center\" messages='false'}\n\n```{.r .cell-code  code-summary=\"testing\"}\n# Visualize the difference scores across different levels of sex\n\n# Create a violin plot to show the distribution of difference scores by sex\n# Jittered points are added to provide a more granular view of individual observations\n# Load necessary libraries\nlibrary(dplyr)\nlibrary(ggplot2)\nlibrary(RColorBrewer)\n\n# Merge the 'sex' variable from the original dataframe 'df' to 'height_diff_data'\nmerged_data <- height_diff_data %>%\n  left_join(df %>% select(src_subject_id, sex), by = \"src_subject_id\")\n\n# Plotting using ggplot2\nggplot(merged_data, aes(x = sex, y = diff, fill = sex)) +\n  geom_violin() +\n  geom_jitter(position = position_jitter(width = 0.2), size = 1, alpha = 0.5) +\n  scale_fill_brewer(palette = \"Set2\") + \n  labs(\n    title = \"Difference Scores by Sex\",\n    x = \"Sex\",\n    y = \"Difference Score\"\n  ) +\n  theme_minimal() + \n  theme(\n    axis.text.x = element_text(angle = 45, hjust = 1),\n    legend.position = \"none\"\n  )\n```\n\n::: {.cell-output-display}\n![](1b_Examples_DifferenceScores_SimpleRegression_files/figure-html/violin-plots-1.png){fig-align='center' width=75%}\n:::\n:::\n\n\nThe violin plot visualizes the distribution of difference scores in children's heights by their sex: Right, Left, and Mixed. Each violin shape provides insight into the density of the data at different height differences, with wider sections representing higher densities of data points. Superimposed jittered points offer a granular view of individual observations. From the plot, it appears that the distributions of height differences across the three handedness categories are somewhat similar, though there might be subtle variations in median and spread.\n\n:::\n:::\n\n## Wrapping Up\n\n::: panel-tabset\n### Write-up {.tabset .tabset-fade .tabset-pills}\n\n::: blue\nDifferences in children's heights between baseline and a subsequent 1-year follow-up, we sought to understand the potential influence of sex on this difference. Descriptive statistics revealed that height differences ranged from a decrease of -51.875 units to an increase of 67 units, with a median difference of 2.25 units and an average difference of approximately 2.3542189 units. Subsequent regression analysis indicated that, when compared to boys, girls had an average increase in height difference of approximately -0.338 units, though this effect was marginally significant (p = 0). Complementary to these findings, violin plots visually underscored the subtle variations in height differences across sex categories, suggesting broadly similar distributions but with nuanced variations in central tendency and spread. In conclusion, while sex exhibited a potential influence on height difference over the year, the observed effect was notably minor.\n\n\n:::\n:::",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}