{
  "hash": "552b82cfd74dfa9cf59105547b79f7c9",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Difference Scores: Paired Samples T-test\"\nauthor: \"Biostatistics Working Group\"\n---\n\n::: {.cell}\n\n:::\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n## Overview\nDifference scores can be used to assess change in a variable across two timepoints. The value of the variable at the first timepoint is substracted from the value at the second timepoint. A one-sample t-test can then be applied to determine whether the mean change is significantly different from zero.\n\nThis example will examine height values obtained across 2 annual measurement occasions in a sample of youth taking part in the ABCD Study. The primary aim is to determine whether height values in the sample, on average, increase across the two timempoints. A difference score will be calculated between participant's height values collected at baseline and again at the 1-year follow-up. Next, a one-sample t-test will be used to test whether the difference score is statistically different than a null hypothesis of zero change. Finally, a visual inspection is further conducted via a scatterplot to graphically represent the relationship between participant's height across assessments.\n\n## Preliminary Setup\n### Load R libraries\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(tidyverse) # Collection of R packages for data science\nlibrary(gtsummary) # Publication-ready tables\nlibrary(rstatix) # Statistical Tests in tidy format\n```\n:::\n\n\n### Descriptives\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndescriptives_table <- df_long %>%\n    select(event, height) %>%\n    mutate(event = factor(event)) %>%\n    tbl_summary(\n        by = event,\n        missing = \"no\",\n        label = list(height ~ \"Height\"),\n        statistic = list(all_continuous() ~ \"{mean} ({sd})\", all_categorical() ~ \"{p}%\"),\n    ) %>%\n    modify_header(all_stat_cols() ~ \"**{level}**<br>N = {n}\") %>%\n    bold_labels() %>%\n    italicize_levels() %>%\n    modify_spanning_header(all_stat_cols() ~ \"**Assessment Wave**\")\ntheme_gtsummary_compact()\n\ndescriptives_table\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"qsjqitzdpi\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#qsjqitzdpi table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#qsjqitzdpi thead, #qsjqitzdpi tbody, #qsjqitzdpi tfoot, #qsjqitzdpi tr, #qsjqitzdpi td, #qsjqitzdpi th {\n  border-style: none;\n}\n\n#qsjqitzdpi p {\n  margin: 0;\n  padding: 0;\n}\n\n#qsjqitzdpi .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 13px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#qsjqitzdpi .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#qsjqitzdpi .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#qsjqitzdpi .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#qsjqitzdpi .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#qsjqitzdpi .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qsjqitzdpi .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#qsjqitzdpi .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#qsjqitzdpi .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#qsjqitzdpi .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#qsjqitzdpi .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#qsjqitzdpi .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#qsjqitzdpi .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#qsjqitzdpi .gt_group_heading {\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#qsjqitzdpi .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#qsjqitzdpi .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#qsjqitzdpi .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#qsjqitzdpi .gt_row {\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#qsjqitzdpi .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qsjqitzdpi .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#qsjqitzdpi .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#qsjqitzdpi .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#qsjqitzdpi .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qsjqitzdpi .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#qsjqitzdpi .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#qsjqitzdpi .gt_last_summary_row {\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qsjqitzdpi .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qsjqitzdpi .gt_first_grand_summary_row {\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#qsjqitzdpi .gt_last_grand_summary_row_top {\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qsjqitzdpi .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#qsjqitzdpi .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qsjqitzdpi .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#qsjqitzdpi .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qsjqitzdpi .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#qsjqitzdpi .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qsjqitzdpi .gt_left {\n  text-align: left;\n}\n\n#qsjqitzdpi .gt_center {\n  text-align: center;\n}\n\n#qsjqitzdpi .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#qsjqitzdpi .gt_font_normal {\n  font-weight: normal;\n}\n\n#qsjqitzdpi .gt_font_bold {\n  font-weight: bold;\n}\n\n#qsjqitzdpi .gt_font_italic {\n  font-style: italic;\n}\n\n#qsjqitzdpi .gt_super {\n  font-size: 65%;\n}\n\n#qsjqitzdpi .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#qsjqitzdpi .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#qsjqitzdpi .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#qsjqitzdpi .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#qsjqitzdpi .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#qsjqitzdpi .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#qsjqitzdpi .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Characteristic&lt;/strong&gt;\"><strong>Characteristic</strong></th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"2\" scope=\"colgroup\" id=\"&lt;strong&gt;Assessment Wave&lt;/strong&gt;\">\n        <span class=\"gt_column_spanner\"><strong>Assessment Wave</strong></span>\n      </th>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Baseline&lt;/strong&gt;&lt;br&gt;N = 11859&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>Baseline</strong><br>N = 11859<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Year_1&lt;/strong&gt;&lt;br&gt;N = 11142&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>Year_1</strong><br>N = 11142<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Height</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">55.2 (3.3)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">57.6 (3.7)</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"3\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span> Mean (SD)</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n## Results\n### Compute Difference Score\nThis code computes a difference score by subtracting participant's height at baseline from height at the 1-year follow-up. Next, a one-sample t-test is conducted to determine whether the mean difference score is different from zero. Model output is provided below, as well as a brief summary of results.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Reshaping data from long to wide\ndf_wide <- df_long %>%\n    pivot_wider(\n        id_cols = id,\n        names_from = event,\n        values_from = height,\n        names_prefix = \"Height_\"\n    )\n\n# Compute the height difference score\ndf_wide <- df_wide %>%\n    mutate(\n        height_diff = Height_Year_1 - Height_Baseline\n    )\n\n# Calculate summary statistics for the difference score\nsummary(df_wide$height_diff)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n    -52       2       2       2       3      67     729 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Compute summary statistics for Height by eventname\nsummary <- df_long %>%\n    group_by(event) %>%\n    get_summary_stats(height, type = \"mean_sd\")\n\ndata.frame(summary)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"event\"],\"name\":[1],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"variable\"],\"name\":[2],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"n\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"mean\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"sd\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Baseline\",\"2\":\"height\",\"3\":\"11859\",\"4\":\"55.2\",\"5\":\"3.33\"},{\"1\":\"Year_1\",\"2\":\"height\",\"3\":\"11142\",\"4\":\"57.6\",\"5\":\"3.65\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nThe summary statistics provide insights into participant's height across two annual assessments. At baseline, the average height is 55.24 inches (sd = 3.33). Over the year, there is an increase of 2.35 inches in average height to 57.59 inches at the time of the 1-year follow-up.\n\n### Conduct t-test on Difference Score\nA one-sample t-test is computed on the difference scores to examine whether there is evidence of change in participant's height between the two timepoints.\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Perform a one-sample t-test on the difference scores for height\nmodel <- t.test(df_wide$height_diff, mu = 0)\nmodel\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  df_wide$height_diff\nt = 99, df = 11135, p-value <2e-16\nalternative hypothesis: true mean is not equal to 0\n95 percent confidence interval:\n 2.32 2.41\nsample estimates:\nmean of x \n     2.37 \n```\n\n\n:::\n:::\n\n\nThe results from the one-sample t-test conducted on the height difference scores reveals an increase in height from Baseline to Year 1. The t-test yields a t-value of 98.86 with a p-value less than <.001, indicating that the average height increase of 2.36 inches is significantly different from zero. Additionally, the 95% confidence interval indicates that the true mean difference score in the population lies between approximately 2.31 to 2.41 inches.\n\n### Model Plots\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Scatterplot to compare height differences across two events\nggplot(df_wide, aes(x = Height_Baseline, y = Height_Year_1)) +\n    geom_point(aes(color = Height_Baseline), alpha = 0.6) + # Color points by event type, adjust for your data\n    labs(\n        x = \"Height at Baseline\",\n        y = \"Height at Year 1\",\n        title = \"Scatterplot of Heights at Baseline and Year 1\",\n        subtitle = \"Each point represents a participant\"\n    ) +\n    theme_minimal() +\n    geom_smooth(method = \"lm\", se = FALSE) + # Add a regression line without confidence interval\n    theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](1a_Examples_DifferenceScores_PairedTtests_files/figure-html/unnamed-chunk-7-1.png){fig-align='center' width=75%}\n:::\n:::\n\n\nThe scatterplot visually depicts the relationship between individuals' heights at baseline and their heights at year 1. Each point on the plot represents an individual, with their baseline height plotted on the x-axis and their year 1 height on the y-axis. A noticeable positive linear trend can be observed, as highlighted by the blue regression line, indicating that those who were taller at baseline generally remained taller at year 1. The strength and direction of this relationship suggests a strong positive association between baseline and year 1 height values.\n\n## Wrapping Up\nThis analysis examined difference scores of participant's height using a one-sample t-test. Findings showed a significant increase in height values over the one-year interval of 2.36 inches, with confidence intervals ranging from 2.31 to 2.41 (t = 98.864, df = 11135, p-value < 2.2e-16). Further, a scatterplot visualizing the relationship between baseline and Year_1 weights showed a strong positive linear trend. This suggests that participants who were taller at baseline generally remained taller at Year_1, reaffirming the consistent growth trend observed in the data.\n\nThis difference score approach used in this example quantifies the change in height values over time within a single group and uses a one-sample t-test to test whether this value differs significanctly from 0. More generally, this approach is often implemented when data used to evalaute change is only available at two timepoints, as more flexible approaches are typically implemented when data from additional (>2) time points is available.",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}