{
  "hash": "444838122e21c83a2b59c4aa68ccc426",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Linear Mixed Models: Random Intercept\"\nauthor: \"Biostatistics Working Group\"\n---\n\n::: {.cell}\n\n:::\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n## Overview\nThe Linear mixed model (LMM) with a random intercept is similar to traditional (fixed-effect) linear regression, extending on this approach by including a subject-specific random-effect that allows each participant to have their own unique intercept value, in addition to the overall mean-level (fixed-effect) intercept value.\n\nThis example will examine trajectories of height obtained across 3 annual measurement occasions in a sample of youth taking part in the ABCD Study. The primary aim is to characterize stability and change in participant's height, while accounting for observations that are clustered within youth over time. The random-intercept LMM will simultaneously estimate an overall sample mean (fixed effect) for the height trajectory's intercept and slope values, as well as subject-specific (random) effects that vary randomly about the mean intercept value.\n\n## Preliminary Setup\n### Load Packages\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(tidyverse) # Collection of R packages for data science\nlibrary(gtsummary) # Publication-ready tables\nlibrary(rstatix) # Statistical Tests in tidy format\nlibrary(lme4) # Linear mixed-effects models\n```\n:::\n\n\n### Descriptives\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndescriptives_table <- df_long %>%\n    select(event, height) %>%\n    mutate(event = factor(event)) %>%\n    tbl_summary(\n        by = event,\n        missing = \"no\",\n        label = list(height ~ \"Height\"),\n        statistic = list(all_continuous() ~ \"{mean} ({sd})\", all_categorical() ~ \"{p}%\"),\n    ) %>%\n    modify_header(all_stat_cols() ~ \"**{level}**<br>N = {n}\") %>%\n    bold_labels() %>%\n    italicize_levels() %>%\n    modify_spanning_header(all_stat_cols() ~ \"**Assessment Wave**\")\ntheme_gtsummary_compact()\n\ndescriptives_table\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"ynyjlaklqv\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ynyjlaklqv table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ynyjlaklqv thead, #ynyjlaklqv tbody, #ynyjlaklqv tfoot, #ynyjlaklqv tr, #ynyjlaklqv td, #ynyjlaklqv th {\n  border-style: none;\n}\n\n#ynyjlaklqv p {\n  margin: 0;\n  padding: 0;\n}\n\n#ynyjlaklqv .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 13px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ynyjlaklqv .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ynyjlaklqv .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ynyjlaklqv .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ynyjlaklqv .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ynyjlaklqv .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ynyjlaklqv .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ynyjlaklqv .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ynyjlaklqv .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ynyjlaklqv .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ynyjlaklqv .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ynyjlaklqv .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ynyjlaklqv .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ynyjlaklqv .gt_group_heading {\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ynyjlaklqv .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ynyjlaklqv .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ynyjlaklqv .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ynyjlaklqv .gt_row {\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ynyjlaklqv .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ynyjlaklqv .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ynyjlaklqv .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ynyjlaklqv .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ynyjlaklqv .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ynyjlaklqv .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ynyjlaklqv .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ynyjlaklqv .gt_last_summary_row {\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ynyjlaklqv .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ynyjlaklqv .gt_first_grand_summary_row {\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ynyjlaklqv .gt_last_grand_summary_row_top {\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ynyjlaklqv .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ynyjlaklqv .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ynyjlaklqv .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ynyjlaklqv .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ynyjlaklqv .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ynyjlaklqv .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ynyjlaklqv .gt_left {\n  text-align: left;\n}\n\n#ynyjlaklqv .gt_center {\n  text-align: center;\n}\n\n#ynyjlaklqv .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ynyjlaklqv .gt_font_normal {\n  font-weight: normal;\n}\n\n#ynyjlaklqv .gt_font_bold {\n  font-weight: bold;\n}\n\n#ynyjlaklqv .gt_font_italic {\n  font-style: italic;\n}\n\n#ynyjlaklqv .gt_super {\n  font-size: 65%;\n}\n\n#ynyjlaklqv .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ynyjlaklqv .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ynyjlaklqv .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ynyjlaklqv .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ynyjlaklqv .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ynyjlaklqv .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ynyjlaklqv .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Characteristic&lt;/strong&gt;\"><strong>Characteristic</strong></th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"3\" scope=\"colgroup\" id=\"&lt;strong&gt;Assessment Wave&lt;/strong&gt;\">\n        <span class=\"gt_column_spanner\"><strong>Assessment Wave</strong></span>\n      </th>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Baseline&lt;/strong&gt;&lt;br&gt;N = 11859&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>Baseline</strong><br>N = 11859<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Year_1&lt;/strong&gt;&lt;br&gt;N = 11142&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>Year_1</strong><br>N = 11142<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Year_2&lt;/strong&gt;&lt;br&gt;N = 9190&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>Year_2</strong><br>N = 9190<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Height</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">55.2 (3.3)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">57.6 (3.7)</td>\n<td headers=\"stat_3\" class=\"gt_row gt_center\">60.2 (3.6)</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"4\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span> Mean (SD)</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n## Results\n### Compute LMM Model with Random Intercepts\nThis code fits a radom-intercept LMM to predict 'Height' across 3 annual visits, accounting for individual-level variability (random effects) of intercept values across participants. Model output is provided below, as well as a brief summary of results.\n\nThis model accounts for individual variability in height by including a random intercept for each subject (id). The output indicates that the model was fit using the REML (Restricted Maximum Likelihood) criterion. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmodel <- lmer(height ~ 1 + event + (1 | id), data = df_long, REML = T)\n\n## Output and summary statistics\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML ['lmerMod']\nFormula: height ~ 1 + event + (1 | id)\n   Data: df_long\n\nREML criterion at convergence: 154311\n\nScaled residuals: \n    Min      1Q  Median      3Q     Max \n-22.541  -0.277  -0.007   0.272  25.590 \n\nRandom effects:\n Groups   Name        Variance Std.Dev.\n id       (Intercept) 9.20     3.03    \n Residual             3.19     1.79    \nNumber of obs: 32191, groups:  id, 11867\n\nFixed effects:\n            Estimate Std. Error t value\n(Intercept)  55.2411     0.0323  1709.2\neventYear_1   2.3648     0.0238    99.3\neventYear_2   5.0188     0.0256   196.3\n\nCorrelation of Fixed Effects:\n            (Intr) evnY_1\neventYear_1 -0.350       \neventYear_2 -0.326  0.456\n```\n\n\n:::\n\n```{.r .cell-code}\nconfint(model, level = 0.95, method = \"Wald\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            2.5 % 97.5 %\n.sig01         NA     NA\n.sigma         NA     NA\n(Intercept) 55.18  55.30\neventYear_1  2.32   2.41\neventYear_2  4.97   5.07\n```\n\n\n:::\n:::\n\n\nThese results show an increasing trajectory of height across the years, with an increase of approximately 2.36 inches in Year 1 and 5.02 inches by Year 2 compared to the baseline, as evidenced by the fixed effects estimates. The random intercepts effect suggests some between-subject variability in particpant's height values at baseline, with a standard deviation of about 3.03 inches. The model's residuals are mostly well-behaved, although the range suggests a few extreme values or outliers.\n\n### Model Plots\nThe following set of plots xxxxx.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Extract fixed effects\nfixed_effects <- fixef(model)\n\n# Prepare data frame for plotting\ndf_long$predicted_height <- predict(model, re.form = NA) # Overall fixed effect predictions\n\n# Calculate individual intercept adjustments\ndf_long$individual_intercept <- predict(model, re.form = ~ (1 | id)) - fixed_effects[1]\n\n# Generate the plot\nggplot(df_long, aes(x = event, y = height)) +\n    geom_line(aes(y = height, color = \"Individual Trajectories\"), alpha = 0.3) +\n    geom_line(aes(y = predicted_height + individual_intercept, group = id, color = \"Adjusted Individual Trajectories\"), alpha = 0.7) +\n    geom_line(aes(x = event, y = predicted_height, group = 1, color = \"Sample Mean Trajectory\"), size = 1.5) +\n    scale_color_manual(values = c(\"Individual Trajectories\" = \"red\", \"Adjusted Individual Trajectories\" = \"grey\", \"Sample Mean Trajectory\" = \"blue\")) +\n    labs(\n        title = \"Individual Trajectories with Fixed Slope and Random Intercepts\",\n        x = \"Event Name\",\n        y = \"Height (inches)\",\n        color = \"Trajectory Type\"\n    ) +\n    theme_minimal() +\n    theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](3a_Examples_LinearMixedModels_files/figure-html/unnamed-chunk-6-1.png){fig-align='center' width=75%}\n:::\n:::\n\n\nThis plot illustrates the change in participant's height across 3 annual measurement occassions. The individual raw data points are shown as red lines, representing the original height measurements, which demonstrate the variability among participants at each time point. These are overlaid with grey lines, which adjust each individual's trajectory to start from their unique intercept while following a common growth pattern indicated by the fixed effects from the model. The blue line represents the sample mean trajectory, calculated from the model's fixed effects, showcasing the average growth trend across all participants. \n\nThe plot shows individual trajectories that vary around the model's predicted values due to random effects, indicating substantial inter-individual variability in baseline heights. On average, participants experienced an increase in height of approximately 2.36 inches from baseline to Year 1 and an additional 2.66 inches from Year 1 to Year 2. The random effects for individual intercepts suggest differences in starting heights, with a standard deviation of 3.03 inches, reflecting the variability in growth patterns among the participants.\n\n## Wrapping Up\nThe random-intercept LMM analysis revealed an increasing pattern of change in children's height measured over 3 annual assessments. The mean intercept value showed an average initial height of 55.24 inches (sd = 3.03) with evidence of individual variability around this (random effect) estimate. An examination of the slope factor revealed year-to-year growth increments of approxmiately 2.5 inches, with the rate of change held constant across all participants. \n\nThe LMM framework used in this example offered the ability to account for individual differences in initial height and the consistent growth patterns over time, demonstrating its utility in handling clustered or correlated data that arise from repeated measurements on the same subjects. More generally, this approach is often particularly useful in developmental studies as it allows for the inclusion of both fixed effects, which estimate common parameters across all individuals, and random effects, which capture unique variations among individuals. This enables a more precise understanding of both the group-level trends and individual-specific trajectories in longitudinal data.\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}