{
  "hash": "c2d9be147440972973252b2e0a085291",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Latent Growth Curve Models\"\nauthor: \"Biostatistics Working Group\"\n---\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n\n## Overview\n\nLatent growth curve models (LGCM) are an analytical tool within the framework of structural equation modeling that enable the examination of change over time. This model type effectively separates the true trajectory of a variable from random measurement error, allowing for the estimation of an underlying growth process. The primary components of LGCM include the intercept, which represents the initial status, and the slope, which reflects the rate of change over time.\n\nThis example investigates a growth trajectory of participant's height, measured across 4 annual assessments in participants from the ABCD Study. Fitting the latent growth curve model will allow for an examination of the initial status (intercept) and rate of change (slope) of height from baseline through successive yearly follow-ups. Each participant's height trajectory is modeled to capture both the starting point and the growth pattern over time. The results are illustrated through growth plots that demonstrate the mean trajectory across the cohort, along with the variability in growth rates among individuals, providing insights into the developmental patterns of height over time.\n\n## Preliminary Setup\n### Load Packages\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse) # Collection of R packages for data science\nlibrary(gtsummary) # Publication-ready tables\nlibrary(rstatix) # Statistical Tests in tidy format\nlibrary(lavaan) # Structural Equation Modeling in R\n```\n:::\n\n\n### Descriptives\n\n::: {.cell}\n\n```{.r .cell-code}\ndescriptives_table <- df_long %>%\n    select(event, height) %>%\n    mutate(event = factor(event)) %>%\n    tbl_summary(\n        by = event,\n        missing = \"no\",\n        label = list(height ~ \"Height\"),\n        statistic = list(all_continuous() ~ \"{mean} ({sd}) )\", all_categorical() ~ \"{p}%\"),\n    ) %>%\n    modify_header(all_stat_cols() ~ \"**{level}**<br>N = {n}\") %>%\n    bold_labels() %>%\n    italicize_levels() %>%\n    modify_spanning_header(all_stat_cols() ~ \"**Assessment Wave**\")\ntheme_gtsummary_compact()\n\ndescriptives_table\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"pngnpgzzyc\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#pngnpgzzyc table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#pngnpgzzyc thead, #pngnpgzzyc tbody, #pngnpgzzyc tfoot, #pngnpgzzyc tr, #pngnpgzzyc td, #pngnpgzzyc th {\n  border-style: none;\n}\n\n#pngnpgzzyc p {\n  margin: 0;\n  padding: 0;\n}\n\n#pngnpgzzyc .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 13px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#pngnpgzzyc .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#pngnpgzzyc .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#pngnpgzzyc .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#pngnpgzzyc .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#pngnpgzzyc .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#pngnpgzzyc .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#pngnpgzzyc .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#pngnpgzzyc .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#pngnpgzzyc .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#pngnpgzzyc .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#pngnpgzzyc .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#pngnpgzzyc .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#pngnpgzzyc .gt_group_heading {\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#pngnpgzzyc .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#pngnpgzzyc .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#pngnpgzzyc .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#pngnpgzzyc .gt_row {\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#pngnpgzzyc .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pngnpgzzyc .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#pngnpgzzyc .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#pngnpgzzyc .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#pngnpgzzyc .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pngnpgzzyc .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#pngnpgzzyc .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#pngnpgzzyc .gt_last_summary_row {\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#pngnpgzzyc .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pngnpgzzyc .gt_first_grand_summary_row {\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#pngnpgzzyc .gt_last_grand_summary_row_top {\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#pngnpgzzyc .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#pngnpgzzyc .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#pngnpgzzyc .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#pngnpgzzyc .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pngnpgzzyc .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#pngnpgzzyc .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pngnpgzzyc .gt_left {\n  text-align: left;\n}\n\n#pngnpgzzyc .gt_center {\n  text-align: center;\n}\n\n#pngnpgzzyc .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#pngnpgzzyc .gt_font_normal {\n  font-weight: normal;\n}\n\n#pngnpgzzyc .gt_font_bold {\n  font-weight: bold;\n}\n\n#pngnpgzzyc .gt_font_italic {\n  font-style: italic;\n}\n\n#pngnpgzzyc .gt_super {\n  font-size: 65%;\n}\n\n#pngnpgzzyc .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#pngnpgzzyc .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#pngnpgzzyc .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#pngnpgzzyc .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#pngnpgzzyc .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#pngnpgzzyc .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#pngnpgzzyc .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Characteristic&lt;/strong&gt;\"><strong>Characteristic</strong></th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"4\" scope=\"colgroup\" id=\"&lt;strong&gt;Assessment Wave&lt;/strong&gt;\">\n        <span class=\"gt_column_spanner\"><strong>Assessment Wave</strong></span>\n      </th>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Baseline&lt;/strong&gt;&lt;br&gt;N = 2818&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>Baseline</strong><br>N = 2818<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Year_1&lt;/strong&gt;&lt;br&gt;N = 2818&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>Year_1</strong><br>N = 2818<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Year_2&lt;/strong&gt;&lt;br&gt;N = 2818&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>Year_2</strong><br>N = 2818<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Year_3&lt;/strong&gt;&lt;br&gt;N = 2818&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>Year_3</strong><br>N = 2818<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Height</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">55.1 (3.6) )</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">57.5 (3.7) )</td>\n<td headers=\"stat_3\" class=\"gt_row gt_center\">60.3 (3.6) )</td>\n<td headers=\"stat_4\" class=\"gt_row gt_center\">62.3 (4.1) )</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"5\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span> Mean (SD) )</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n## Results \n### Compute Latent Growth Curve Model\nThe code below is used to compute a growth curve model to investigate changes in height across four annual assessments. This statistical approach provides insights into how much individuals vary around the average trajectory and the consistency of their growth patterns across time. This model estimates an overall intercept, representing the initial status, and a slope that captures the rate of growth across time points. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Reshape data from long to wide format\ndf_wide <- df_long %>%\n    pivot_wider(\n        id_cols = c(id),\n        names_from = event,\n        values_from = height,\n        names_prefix = \"Height_\"\n    )\n\ndf_wide <- na.omit(df_wide)\n\nmodel <- \" i =~ 1*Height_Baseline + 1*Height_Year_1 + 1*Height_Year_2 + 1*Height_Year_3\n           s =~ 0*Height_Baseline + 1*Height_Year_1 + 2*Height_Year_2 + 3*Height_Year_3\n\n           # Intercept and slope variances\n           i ~~ i\n           s ~~ s\n\n           # Residual variances for each observed variable\n           Height_Baseline ~~ var_baseline*Height_Baseline\n           Height_Year_1 ~~ var_year1*Height_Year_1\n           Height_Year_2 ~~ var_year2*Height_Year_2\n           Height_Year_3 ~~ var_year3*Height_Year_3\n\"\n\nfit <- growth(model, data = df_wide)\nsummary(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nlavaan 0.6.16 ended normally after 97 iterations\n\n  Estimator                                         ML\n  Optimization method                           NLMINB\n  Number of model parameters                         9\n\n  Number of observations                          2818\n\nModel Test User Model:\n                                                      \n  Test statistic                               126.998\n  Degrees of freedom                                 5\n  P-value (Chi-square)                           0.000\n\nParameter Estimates:\n\n  Standard errors                             Standard\n  Information                                 Expected\n  Information saturated (h1) model          Structured\n\nLatent Variables:\n                   Estimate  Std.Err  z-value  P(>|z|)\n  i =~                                                \n    Height_Baselin    1.000                           \n    Height_Year_1     1.000                           \n    Height_Year_2     1.000                           \n    Height_Year_3     1.000                           \n  s =~                                                \n    Height_Baselin    0.000                           \n    Height_Year_1     1.000                           \n    Height_Year_2     2.000                           \n    Height_Year_3     3.000                           \n\nCovariances:\n                   Estimate  Std.Err  z-value  P(>|z|)\n  i ~~                                                \n    s                -0.118    0.089   -1.319    0.187\n\nIntercepts:\n                   Estimate  Std.Err  z-value  P(>|z|)\n   .Height_Baselin    0.000                           \n   .Height_Year_1     0.000                           \n   .Height_Year_2     0.000                           \n   .Height_Year_3     0.000                           \n    i                55.157    0.065  846.256    0.000\n    s                 2.491    0.020  122.967    0.000\n\nVariances:\n                   Estimate  Std.Err  z-value  P(>|z|)\n    i                 9.391    0.334   28.080    0.000\n    s                 0.310    0.040    7.697    0.000\n   .Hght_Bs (vr_b)    3.489    0.182   19.214    0.000\n   .Hgh_Y_1 (vr_1)    3.870    0.132   29.282    0.000\n   .Hgh_Y_2 (vr_2)    2.089    0.100   20.972    0.000\n   .Hgh_Y_3 (vr_3)    6.297    0.234   26.963    0.000\n```\n\n\n:::\n:::\n\n\nThe results from the latent growth curve analysis show an increasing pattern of mean change in participant's height across assessments (slope = 2.491, p<.001). In addition, the model identified significant variability in both the intercept (estimate = 9.39, se=.33, p<.001), which represents initial height and the slope (estimate = .31, se=.04, p<.001), which measures growth over time. This indicates substantial differences in starting heights and growth rates among individuals. The covariance between the intercept and slope was not statistically significant (estimate = -.11, p = .18), suggesting initial height does not influence the rate of growth.\n\n### Model Plots\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plotting the height data over time from the df_long dataframe\nggplot(df_long, aes(x = event, y = height, group = id)) +\n    geom_line(alpha = 0.4, aes(color = \"Actual Height\"), size = 0.5) + # Lines to connect data points for each participant\n    geom_point(alpha = 0.6, color = \"blue\") + # Points for actual heights\n    scale_x_discrete(limits = c(\"Baseline\", \"Year_1\", \"Year_2\", \"Year_3\")) + # Ensuring the order of events\n    labs(\n        title = \"Actual Height Growth Across Timepoints\",\n        x = \"Time (Years from Baseline)\",\n        y = \"Height (inches)\"\n    ) +\n    theme_minimal() +\n    theme(legend.position = \"bottom\") # Adjust legend position\n```\n\n::: {.cell-output-display}\n![](10_Examples_LatentGrowthCurveModels_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nThis plot visualizes the height trajectories across four annual timepoints. Each line represents an individual participant's height trajectory showing overall trends while maintaining focus on individual variations. Blue points mark the actual height measurements at each timepoint, providing a clear view of the data distribution and growth patterns over time. This graph highlights both the general trend of increasing height and the individual differences in growth rates among participants.\n\n## Wrapping Up\nThis analysis employed a latent growth curve model (LGCM) framework to examine participants' heights across multiple assessment points. Results revealed an increasing trend in average height changes over time, with a slope parameter of 2.49 (p<.001), indicating a steady growth across all assessments. Significant variability was observed both in the intercept, with an estimate of 9.39 (se = .33, p<.001), representing the initial height, and in the slope, with an estimate of .31 (se = .04, p<.001), which measures growth over time. This highlights notable individual differences in starting heights and growth rates. Furthermore, the lack of a statistically significant covariance between the intercept and slope (estimate = -.11, p = .18) suggests that the initial height does not influence subsequent growth rates.\n\nLatent growth curve modeling provides a powerful tool for evaluating patterns of growth, allowing for the differentiation between average growth trajectories and individual variability. This method is able to parse out complex relationships, underscoring its utility in longitudinal data analysis, enhancing our interpretation of how individuals change over time.\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}