{
  "hash": "8fbed91f91a1181943421217fed4f493",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Generalized Estimating Equations\"\nauthor: \"Biostatistics Working Group\"\n---\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n\n## Overview\n\nGeneralized Estimating Equations (GEE) are an extension of generalized linear models used for analyzing longitudinal and other correlated response data. GEEs provide a method for estimating the parameters of a generalized linear model with and are particularly useful when dealing with repeated measurements or clustered data, offering robust standard errors that account for within-subject correlations.\n\nThis example will examine height across 3 annual measurement occasions in a sample of youth taking part in the ABCD Study. The primary aim is to characterize the average growth pattern in height over time at the population level. GEEs will be employed to estimate the mean height at each time point, accounting for the correlation of repeated measurements within individuals. This approach will help us understand how height changes over time while providing robust estimates that account for the inherent correlation in the repeated measures data.\n\n## Preliminary Setup\n### Load R libraries\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)    # Collection of R packages for data science\nlibrary(rstatix)      # Pipe-friendly framework for basic statistical tests\nlibrary(geepack)      # Generalized Estimating Equations (GEE) analysis\nlibrary(gtsummary) # Publication-ready tables\n```\n:::\n\n\n### Descriptives\n\n::: {.cell}\n\n```{.r .cell-code}\ndescriptives_table <- df_long %>%\n    select(event, height) %>%\n    mutate(event = factor(event)) %>%\n    tbl_summary(\n        by = event,\n        missing = \"no\",\n        label = list(height ~ \"Height\"),\n        statistic = list(all_continuous() ~ \"{mean} ({sd})\", all_categorical() ~ \"{p}%\"),\n    ) %>%\n    modify_header(all_stat_cols() ~ \"**{level}**<br>N = {n}\") %>%\n    bold_labels() %>%\n    italicize_levels() %>%\n    modify_spanning_header(all_stat_cols() ~ \"**Assessment Wave**\")\ntheme_gtsummary_compact()\n\ndescriptives_table\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"qxklddqxwv\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#qxklddqxwv table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#qxklddqxwv thead, #qxklddqxwv tbody, #qxklddqxwv tfoot, #qxklddqxwv tr, #qxklddqxwv td, #qxklddqxwv th {\n  border-style: none;\n}\n\n#qxklddqxwv p {\n  margin: 0;\n  padding: 0;\n}\n\n#qxklddqxwv .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 13px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#qxklddqxwv .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#qxklddqxwv .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#qxklddqxwv .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#qxklddqxwv .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#qxklddqxwv .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qxklddqxwv .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#qxklddqxwv .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#qxklddqxwv .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#qxklddqxwv .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#qxklddqxwv .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#qxklddqxwv .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#qxklddqxwv .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#qxklddqxwv .gt_group_heading {\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#qxklddqxwv .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#qxklddqxwv .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#qxklddqxwv .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#qxklddqxwv .gt_row {\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#qxklddqxwv .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qxklddqxwv .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#qxklddqxwv .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#qxklddqxwv .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#qxklddqxwv .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qxklddqxwv .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#qxklddqxwv .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#qxklddqxwv .gt_last_summary_row {\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qxklddqxwv .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qxklddqxwv .gt_first_grand_summary_row {\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#qxklddqxwv .gt_last_grand_summary_row_top {\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qxklddqxwv .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#qxklddqxwv .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qxklddqxwv .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#qxklddqxwv .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qxklddqxwv .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#qxklddqxwv .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qxklddqxwv .gt_left {\n  text-align: left;\n}\n\n#qxklddqxwv .gt_center {\n  text-align: center;\n}\n\n#qxklddqxwv .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#qxklddqxwv .gt_font_normal {\n  font-weight: normal;\n}\n\n#qxklddqxwv .gt_font_bold {\n  font-weight: bold;\n}\n\n#qxklddqxwv .gt_font_italic {\n  font-style: italic;\n}\n\n#qxklddqxwv .gt_super {\n  font-size: 65%;\n}\n\n#qxklddqxwv .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#qxklddqxwv .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#qxklddqxwv .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#qxklddqxwv .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#qxklddqxwv .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#qxklddqxwv .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#qxklddqxwv .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Characteristic&lt;/strong&gt;\"><strong>Characteristic</strong></th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"4\" scope=\"colgroup\" id=\"&lt;strong&gt;Assessment Wave&lt;/strong&gt;\">\n        <span class=\"gt_column_spanner\"><strong>Assessment Wave</strong></span>\n      </th>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Baseline&lt;/strong&gt;&lt;br&gt;N = 2818&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>Baseline</strong><br>N = 2818<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Year_1&lt;/strong&gt;&lt;br&gt;N = 2818&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>Year_1</strong><br>N = 2818<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Year_2&lt;/strong&gt;&lt;br&gt;N = 2818&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>Year_2</strong><br>N = 2818<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Year_3&lt;/strong&gt;&lt;br&gt;N = 2818&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>Year_3</strong><br>N = 2818<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Height</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">55.1 (3.6)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">57.5 (3.7)</td>\n<td headers=\"stat_3\" class=\"gt_row gt_center\">60.3 (3.6)</td>\n<td headers=\"stat_4\" class=\"gt_row gt_center\">62.3 (4.1)</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"5\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span> Mean (SD)</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n## Results\n### Compute Generalized Estimating Equations Analysis\nThis code fits a Generalized Estimating Equations (GEE) model to predict 'Height' across 3 annual visits, accounting for within-subject correlation of repeated measurements. The model output is provided below, along with a summary of results. This approach uses GEEs to estimate the population-averaged effects, providing robust standard errors and accommodating the correlation structure of the repeated height measurements.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- geeglm(height ~ event, data = df_long, id = id, family = gaussian(), corstr = \"exchangeable\")\n\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\ngeeglm(formula = height ~ event, family = gaussian(), data = df_long, \n    id = id, corstr = \"exchangeable\")\n\n Coefficients:\n            Estimate  Std.err   Wald Pr(>|W|)    \n(Intercept) 55.12374  0.06700 676923   <2e-16 ***\neventYear_1  2.41098  0.05233   2122   <2e-16 ***\neventYear_2  5.19716  0.04933  11099   <2e-16 ***\neventYear_3  7.20428  0.06614  11865   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation structure = exchangeable \nEstimated Scale Parameters:\n\n            Estimate Std.err\n(Intercept)    13.86  0.7955\n  Link = identity \n\nEstimated Correlation Parameters:\n      Estimate Std.err\nalpha   0.6806 0.03678\nNumber of clusters:   2818  Maximum cluster size: 4 \n```\n\n\n:::\n:::\n\n\nThese results indicate a significant increase in height across the years, with an increase of approximately 2.41 inches in Year 1 and 5.20 inches by Year 2 compared to the baseline, as evidenced by the fixed effects estimates. The exchangeable correlation structure suggests a consistent correlation between repeated measurements within individuals, with an estimated correlation parameter (alpha) of 0.681. The significant Wald statistics and p-values (< 2e-16) for each year indicate strong evidence of height changes over time in the population.\n\n### Model Plots\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit the GEE model\nmodel <- geeglm(height ~ event, data = df_long, id = id, family = gaussian(), corstr = \"exchangeable\")\n\n# Extract the predicted means and standard errors\npredicted_values <- data.frame(\n  event = unique(df_long$event),\n  mean_height = predict(model, newdata = data.frame(event = unique(df_long$event)), type = \"response\"),\n  se = sqrt(diag(vcov(model)))\n)\n\n# Calculate confidence intervals\npredicted_values <- predicted_values %>%\n  mutate(\n    ci_lower = mean_height - 1.96 * se,\n    ci_upper = mean_height + 1.96 * se\n  )\n\n# Generate the plot\nggplot(predicted_values, aes(x = event, y = mean_height)) +\n  geom_line(color = \"blue\", linewidth = 1) +\n  geom_point(color = \"blue\", size = 3) +\n  geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), width = 0.2, color = \"blue\") +\n  labs(\n    title = \"Mean Height Across Time Points with Confidence Intervals (GEE)\",\n    x = \"Time Point\",\n    y = \"Mean Height (inches)\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](6_Examples_GeneralizedEstimatingEquations_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nThis plot illustrates the mean height of participants across three annual measurement occasions, as estimated by the generalized estimating equations (GEE) model. The blue line and points represent the estimated mean height at each time point, while the error bars show the 95% confidence intervals around these estimates.\n\nThe plot reveals a clear increasing trend in height over time, with mean height values rising at each subsequent measurement occasion. The confidence intervals provide a sense of the variability and precision of these mean estimates, indicating that the observed increase in height is statistically significant. This visualization highlights the overall growth pattern in the sample, capturing the population-averaged trends effectively.\n\n## Wrapping Up\n\nThe marginal model analysis using Generalized Estimating Equations (GEE) revealed a significant increase in children's height measured over 3 annual assessments. The mean intercept value showed an average initial height of 55.12 inches. The fixed effects estimates indicated year-to-year growth increments of approximately 2.41 inches in Year 1 and 5.20 inches by Year 2 compared to the baseline.\n\nThe GEE framework employed in this example captured the population-averaged trends while accounting for the correlation of repeated measurements within individuals. The exchangeable correlation structure suggested that measurements were consistently correlated within individuals, with an estimated correlation parameter (alpha) of 0.681. The significant Wald statistics and p-values (< 2e-16) provided strong evidence of height changes over time.\n\nThe marginal model approach is particularly useful in developmental studies as it estimates common parameters across all individuals, offering a clear understanding of population-level trends in longitudinal data. This method is valuable for examining average growth patterns while accounting for the correlation in repeated measurements, providing insights into the overall changes in height over time.\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}