{
  "hash": "3d37b6572b164df3274459e61bdff164",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Marginal Models\"\nauthor: \"Biostatistics Working Group\"\n---\n\n::: {.cell}\n\n:::\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n## Overview\nMarginal models, also known as population-averaged models, are used in the analysis of longitudinal data where the focus is on the overall population effect rather than individual-specific effects. These models account for the correlation between repeated measures within subjects by using generalized estimating equations (GEE) to provide robust standard errors and efficient parameter estimates.\n\nThis example will examine height across 3 annual measurement occasions in a sample of youth taking part in the ABCD Study. The primary aim is to characterize the average growth pattern in height over time at the population level. Marginal models will be employed to estimate the overall mean height at each time point, while accounting for the correlation of repeated measurements within individuals, thus providing a comprehensive understanding of height changes across the entire sample.\n\n## Preliminary Setup\n\n### Load R libraries\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(tidyverse)    # Collection of R packages for data science\nlibrary(lme4)         # Linear mixed-effects models\nlibrary(geepack)      # Generalized Estimating Equations (GEE) analysis\nlibrary(report)       # Easy reporting of regression analyses\nlibrary(broom)        # Tidy and augment statistical models output\nlibrary(gridExtra)    # Arrange multiple grid-based plots on a page\nlibrary(easystats)    #\nlibrary(gtsummary)    #\nlibrary(marginaleffects) #\n```\n:::\n\n\n### Descriptives\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndescriptives_table <- df_long %>%\n    select(event, height) %>%\n    mutate(event = factor(event)) %>%\n    tbl_summary(\n        by = event,\n        missing = \"no\",\n        label = list(height ~ \"Height\"),\n        statistic = list(all_continuous() ~ \"{mean} ({sd})\", all_categorical() ~ \"{p}%\"),\n    ) %>%\n    modify_header(all_stat_cols() ~ \"**{level}**<br>N = {n}\") %>%\n    bold_labels() %>%\n    italicize_levels() %>%\n    modify_spanning_header(all_stat_cols() ~ \"**Assessment Wave**\")\ntheme_gtsummary_compact()\n\ndescriptives_table\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"gjxbjdxtlg\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#gjxbjdxtlg table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#gjxbjdxtlg thead, #gjxbjdxtlg tbody, #gjxbjdxtlg tfoot, #gjxbjdxtlg tr, #gjxbjdxtlg td, #gjxbjdxtlg th {\n  border-style: none;\n}\n\n#gjxbjdxtlg p {\n  margin: 0;\n  padding: 0;\n}\n\n#gjxbjdxtlg .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 13px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#gjxbjdxtlg .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#gjxbjdxtlg .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#gjxbjdxtlg .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#gjxbjdxtlg .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#gjxbjdxtlg .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gjxbjdxtlg .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#gjxbjdxtlg .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#gjxbjdxtlg .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#gjxbjdxtlg .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#gjxbjdxtlg .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#gjxbjdxtlg .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#gjxbjdxtlg .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#gjxbjdxtlg .gt_group_heading {\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#gjxbjdxtlg .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#gjxbjdxtlg .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#gjxbjdxtlg .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#gjxbjdxtlg .gt_row {\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#gjxbjdxtlg .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gjxbjdxtlg .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#gjxbjdxtlg .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#gjxbjdxtlg .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#gjxbjdxtlg .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gjxbjdxtlg .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#gjxbjdxtlg .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#gjxbjdxtlg .gt_last_summary_row {\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gjxbjdxtlg .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gjxbjdxtlg .gt_first_grand_summary_row {\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#gjxbjdxtlg .gt_last_grand_summary_row_top {\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gjxbjdxtlg .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#gjxbjdxtlg .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#gjxbjdxtlg .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#gjxbjdxtlg .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gjxbjdxtlg .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#gjxbjdxtlg .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#gjxbjdxtlg .gt_left {\n  text-align: left;\n}\n\n#gjxbjdxtlg .gt_center {\n  text-align: center;\n}\n\n#gjxbjdxtlg .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#gjxbjdxtlg .gt_font_normal {\n  font-weight: normal;\n}\n\n#gjxbjdxtlg .gt_font_bold {\n  font-weight: bold;\n}\n\n#gjxbjdxtlg .gt_font_italic {\n  font-style: italic;\n}\n\n#gjxbjdxtlg .gt_super {\n  font-size: 65%;\n}\n\n#gjxbjdxtlg .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#gjxbjdxtlg .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#gjxbjdxtlg .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#gjxbjdxtlg .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#gjxbjdxtlg .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#gjxbjdxtlg .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#gjxbjdxtlg .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Characteristic&lt;/strong&gt;\"><strong>Characteristic</strong></th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"4\" scope=\"colgroup\" id=\"&lt;strong&gt;Assessment Wave&lt;/strong&gt;\">\n        <span class=\"gt_column_spanner\"><strong>Assessment Wave</strong></span>\n      </th>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Baseline&lt;/strong&gt;&lt;br&gt;N = 2818&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>Baseline</strong><br>N = 2818<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Year_1&lt;/strong&gt;&lt;br&gt;N = 2818&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>Year_1</strong><br>N = 2818<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Year_2&lt;/strong&gt;&lt;br&gt;N = 2818&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>Year_2</strong><br>N = 2818<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Year_3&lt;/strong&gt;&lt;br&gt;N = 2818&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>Year_3</strong><br>N = 2818<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Height</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">55.1 (3.6)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">57.5 (3.7)</td>\n<td headers=\"stat_3\" class=\"gt_row gt_center\">60.3 (3.6)</td>\n<td headers=\"stat_4\" class=\"gt_row gt_center\">62.3 (4.1)</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"5\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span> Mean (SD)</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n## Results\n### Compute Marginal Model Analysis\nThis code fits a Marginal Model to predict 'Height' across 3 annual visits, focusing on the overall population-level effect. The model output is provided below, along with a summary of results. This approach accounts for the correlation between repeated measurements within individuals using generalized estimating equations (GEE), providing robust standard errors and efficient parameter estimates for the average height at each time point.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndf_long <- df_long %>%\n  filter(!is.na(height) & !is.na(event) & !is.na(id))\n\n# Fitting the longitudinal marginal model\nmodel <- geeglm(height ~ event, data = df_long, id = id, family = gaussian(), corstr = \"exchangeable\")\n\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\ngeeglm(formula = height ~ event, family = gaussian(), data = df_long, \n    id = id, corstr = \"exchangeable\")\n\n Coefficients:\n            Estimate Std.err   Wald Pr(>|W|)    \n(Intercept)  55.1237  0.0670 676923   <2e-16 ***\neventYear_1   2.4110  0.0523   2122   <2e-16 ***\neventYear_2   5.1972  0.0493  11099   <2e-16 ***\neventYear_3   7.2043  0.0661  11865   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation structure = exchangeable \nEstimated Scale Parameters:\n\n            Estimate Std.err\n(Intercept)     13.9   0.796\n  Link = identity \n\nEstimated Correlation Parameters:\n      Estimate Std.err\nalpha    0.681  0.0368\nNumber of clusters:   2818  Maximum cluster size: 4 \n```\n\n\n:::\n:::\n\n\nThese results show a significant increase in height across the years, with an estimated increase of approximately 2.41 inches in Year 1 and 5.20 inches by Year 2 compared to the baseline, as indicated by the fixed effects estimates. The correlation structure of the repeated measurements is modeled using an exchangeable correlation matrix, which suggests that the measurements are equally correlated within individuals. The significant Wald statistics and p-values (< 2e-16) for each year indicate strong evidence of height changes over time in the population.\n\n### Model Plots\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Calculate mean height and confidence intervals for each time point\nsummary_data <- df_long %>%\n  group_by(event) %>%\n  summarize(\n    mean_height = mean(height, na.rm = TRUE),\n    ci_lower = mean_height - qt(0.975, df = n() - 1) * sd(height, na.rm = TRUE) / sqrt(n()),\n    ci_upper = mean_height + qt(0.975, df = n() - 1) * sd(height, na.rm = TRUE) / sqrt(n())\n  )\n\n# Generate the plot\nggplot(summary_data, aes(x = event, y = mean_height)) +\n  geom_line(color = \"blue\", size = 1) +\n  geom_point(color = \"blue\", size = 3) +\n  geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), width = 0.2, color = \"blue\") +\n  labs(\n    title = \"Mean Height Across Time Points with Confidence Intervals\",\n    x = \"Time Point\",\n    y = \"Mean Height (inches)\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](5_Examples_MarginalModels_files/figure-html/unnamed-chunk-6-1.png){fig-align='center' width=75%}\n:::\n:::\n\nThis plot illustrates the mean height of participants across the three annual measurement occasions, along with 95% confidence intervals. The blue line and points represent the average height at each time point, while the error bars show the range within which we are 95% confident the true mean height lies.\n\nThe plot reveals a clear increasing trend in height over time, with mean height values rising at each subsequent measurement occasion. The confidence intervals provide a sense of the variability and precision of these mean estimates, indicating that the observed increase in height is statistically significant. This visualization highlights the overall growth pattern in the sample, capturing the population-level trends effectively.\n\n## Wrapping Up\nThe marginal model analysis revealed a significant increase in children's height measured over 3 annual assessments. The mean intercept value showed an average initial height of 55.12 inches, with year-to-year growth increments of approximately 2.41 inches in Year 1 and 5.20 inches by Year 2 compared to the baseline.\n\nThe marginal model framework, using generalized estimating equations (GEE), effectively captured the population-averaged trends while accounting for the correlation of repeated measurements within individuals. This approach demonstrated its utility in handling clustered data from repeated measurements on the same subjects. The exchangeable correlation structure indicated that the measurements were equally correlated within individuals, and the significant Wald statistics provided strong evidence of height changes over time.\n\nOverall, the marginal model approach is particularly useful in developmental studies as it estimates common parameters across all individuals, offering a clear understanding of population-level trends in longitudinal data. This method is valuable for examining average growth patterns while accounting for the correlation in repeated measurements.\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}