{
  "hash": "722d355c6f95503f62550100df34332e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Residualized Change Scores\"\nauthor: \"Biostatistics Working Group\"\n---\n\n\n# Mulitple Regression {.unnumbered}\n\n## Overview\n\n<p>\n\nThis example assesses whether height, measured at the 1-Year follow-up (T1) in a subsample of ABCD participants, is predicted by weight and height measured at baseline (T0). A visual inspection is further conducted via a scatterplot to graphically represent the relationship between height at Year_1 and weight at baseline, controlling for height at baseline. The ensuing analysis and interpretations are detailed in the subsequent sections.\n\n</p>\n\n## Preliminary Setup\n\n::: panel-tabset\n### Install Packages {.tabset .tabset-fade .tabset-pills}\n\n::: blue\n> **This code installs the r packages necessary for this example, if\n> they are not already installed**\n\n\n::: {.cell messages='false'}\n\n```{.r .cell-code}\n# Create a list of required packages\npackages_required <- c(\"tidyverse\",\"easystats\",\"lme4\",\"gtsummary\",\"report\",\"broom\",\"gridExtra\")\n\n# Check which packages are not installed and install them\npackages_to_install <- setdiff(packages_required, rownames(installed.packages()))\nif (length(packages_to_install) > 0) {\n    install.packages(packages_to_install)\n}\n\n# Load the required packages\nlapply(packages_required, library, character.only = TRUE)\n```\n:::\n\n:::\n\n### Load Packages\n\n::: blue\n**This code loads the r libraries necessary for this example**\n\n\n::: {.cell messages='false'}\n\n```{.r .cell-code}\nlibrary(tidyverse)    # Collection of R packages for data science\nlibrary(easystats)    # Collection of R packages statistical modeling, visualization, and reporting\nlibrary(gtsummary)    # Publication-ready tables\nlibrary(report)       # Easy reporting of regression analyses\nlibrary(broom)        # Tidy and augment statistical models output\nlibrary(gridExtra)    # Arrange multiple grid-based plots on a page\n```\n:::\n\n:::\n\n\n::: {.cell messages='false'}\n\n:::\n\n:::\n\n## Descriptives Overview\n\n::: panel-tabset\n### Read and View Data {.tabset .tabset-fade .tabset-pills}\n\n::: blue\n**This code reads in and shows the data to be used in the current\nexample**\n\n\n::: {.cell layout-align=\"center\" messages='false'}\n\n```{.r .cell-code}\n# Set the data paths\ndata_path_1 <- \"/Users/shawes/ABCD/data/rds/abcd_5.0_rds/demo5.0.rds\"\ndata_path_2 <- \"/Users/shawes/ABCD/data/rds/abcd_5.0_rds/core-rds-5.0/non-imaging_excluding_nt_5.0.rds\"\n\n# Read the data\ndata_demographics <- readRDS(data_path_1)\ndata_nonimaging <- readRDS(data_path_2)\n\n# Subset the nonimaging data to include desired variables\nselected_vars <- c(\"src_subject_id\", \"eventname\", \"nihtbx_totalcomp_fc\", \"anthroweightcalc\", \"anthroheightcalc\")\nsubset_data <- data_nonimaging[, selected_vars]\n\nlibrary(dplyr)\n# # Merge the datasets on 'src_subject_id' and 'eventname'\nmerged_data <- data_demographics %>%\n  full_join(subset_data, by = c(\"src_subject_id\", \"eventname\"))\n\n# Inspect the merged data structure\nstr(merged_data)\n\n# Define event names to be retained in the analysis and convert variables to appropriate data types\neventnames_to_include <- c(\"baseline_year_1_arm_1\",\n                           \"1_year_follow_up_y_arm_1\",\n                           \"2_year_follow_up_y_arm_1\",\n                           \"3_year_follow_up_y_arm_1\",\n                           \"4_year_follow_up_y_arm_1\")\n\ndf <- merged_data %>%\n  filter(eventname %in% eventnames_to_include) %>%\n  mutate(\n    src_subject_id = as.factor(src_subject_id),\n    eventname = factor(eventname, levels = eventnames_to_include, ordered = TRUE),\n    age = as.numeric(age),\n    sex = as.factor(sex),\n    race.4level = as.factor(race.4level),\n    hisp = as.factor(hisp),\n    high.educ.bl = as.factor(high.educ.bl),\n    household.income.bl = as.factor(household.income.bl),\n    acs_raked_propensity_score = as.numeric(acs_raked_propensity_score),\n    rel_family_id.bl = as.factor(rel_family_id.bl),\n    site_id_l = as.factor(site_id_l),\n    nihtbx_totalcomp_fc = as.numeric(nihtbx_totalcomp_fc),\n    anthroweightcalc = as.numeric(anthroweightcalc),\n    anthroheightcalc = as.numeric(anthroheightcalc)\n  ) %>%\n  # Exclude cases from unused assessment waves\n  filter(!is.na(eventname))\n```\n:::\n\n:::\n\n### Descriptives\n\n::: blue\n**This code creates a descriptives table**\n\n\n::: {.cell layout-align=\"center\" messages='false'}\n\n```{.r .cell-code}\ndescriptives_table <- df %>%\n  select(eventname, sex, race.4level, hisp, anthroweightcalc) %>%\n  mutate(eventname = factor(eventname, labels = c(\"Baseline\", \"Year 1\",\"Year 2\",\"Year 3\",\"Year 4\"))) %>%\n  mutate(sex = factor(sex, labels = c(\"Female\", \"Male\"))) %>%\n  tbl_summary(\n    by = eventname,\n    missing = \"no\",\n    label = list(sex ~ \"Sex\", race.4level ~ \"Race\", hisp ~ \"Hispanic\", \n                 anthroweightcalc ~ \"Weight\"),\n    statistic = list(all_continuous() ~ \"{mean} ({sd}) )\", all_categorical() ~ \"{p}%\"),\n  ) %>%\nmodify_header(all_stat_cols() ~ \"**{level}**<br>N = {n}\") %>%\n  bold_labels() %>%\n  italicize_levels() %>%\n  modify_spanning_header(all_stat_cols() ~ \"**Assessment Wave**\")\ntheme_gtsummary_compact()\n\ndescriptives_table\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"jzsioatyxk\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#jzsioatyxk table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#jzsioatyxk thead, #jzsioatyxk tbody, #jzsioatyxk tfoot, #jzsioatyxk tr, #jzsioatyxk td, #jzsioatyxk th {\n  border-style: none;\n}\n\n#jzsioatyxk p {\n  margin: 0;\n  padding: 0;\n}\n\n#jzsioatyxk .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 13px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#jzsioatyxk .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#jzsioatyxk .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#jzsioatyxk .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#jzsioatyxk .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jzsioatyxk .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jzsioatyxk .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jzsioatyxk .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#jzsioatyxk .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#jzsioatyxk .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#jzsioatyxk .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#jzsioatyxk .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#jzsioatyxk .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#jzsioatyxk .gt_group_heading {\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#jzsioatyxk .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#jzsioatyxk .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#jzsioatyxk .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#jzsioatyxk .gt_row {\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#jzsioatyxk .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jzsioatyxk .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#jzsioatyxk .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#jzsioatyxk .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#jzsioatyxk .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jzsioatyxk .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#jzsioatyxk .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#jzsioatyxk .gt_last_summary_row {\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jzsioatyxk .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jzsioatyxk .gt_first_grand_summary_row {\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#jzsioatyxk .gt_last_grand_summary_row_top {\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jzsioatyxk .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#jzsioatyxk .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jzsioatyxk .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jzsioatyxk .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jzsioatyxk .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jzsioatyxk .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jzsioatyxk .gt_left {\n  text-align: left;\n}\n\n#jzsioatyxk .gt_center {\n  text-align: center;\n}\n\n#jzsioatyxk .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#jzsioatyxk .gt_font_normal {\n  font-weight: normal;\n}\n\n#jzsioatyxk .gt_font_bold {\n  font-weight: bold;\n}\n\n#jzsioatyxk .gt_font_italic {\n  font-style: italic;\n}\n\n#jzsioatyxk .gt_super {\n  font-size: 65%;\n}\n\n#jzsioatyxk .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#jzsioatyxk .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#jzsioatyxk .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#jzsioatyxk .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#jzsioatyxk .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#jzsioatyxk .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#jzsioatyxk .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Characteristic&lt;/strong&gt;\"><strong>Characteristic</strong></th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"5\" scope=\"colgroup\" id=\"&lt;strong&gt;Assessment Wave&lt;/strong&gt;\">\n        <span class=\"gt_column_spanner\"><strong>Assessment Wave</strong></span>\n      </th>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Baseline&lt;/strong&gt;&lt;br&gt;N = 11868&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>Baseline</strong><br>N = 11868<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Year 1&lt;/strong&gt;&lt;br&gt;N = 11220&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>Year 1</strong><br>N = 11220<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Year 2&lt;/strong&gt;&lt;br&gt;N = 10973&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>Year 2</strong><br>N = 10973<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Year 3&lt;/strong&gt;&lt;br&gt;N = 10336&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>Year 3</strong><br>N = 10336<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Year 4&lt;/strong&gt;&lt;br&gt;N = 4754&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>Year 4</strong><br>N = 4754<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Sex</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"></td>\n<td headers=\"stat_3\" class=\"gt_row gt_center\"></td>\n<td headers=\"stat_4\" class=\"gt_row gt_center\"></td>\n<td headers=\"stat_5\" class=\"gt_row gt_center\"></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-style: italic;\">    Female</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">48%</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">48%</td>\n<td headers=\"stat_3\" class=\"gt_row gt_center\">48%</td>\n<td headers=\"stat_4\" class=\"gt_row gt_center\">47%</td>\n<td headers=\"stat_5\" class=\"gt_row gt_center\">48%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-style: italic;\">    Male</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">52%</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">52%</td>\n<td headers=\"stat_3\" class=\"gt_row gt_center\">52%</td>\n<td headers=\"stat_4\" class=\"gt_row gt_center\">53%</td>\n<td headers=\"stat_5\" class=\"gt_row gt_center\">52%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Race</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"></td>\n<td headers=\"stat_3\" class=\"gt_row gt_center\"></td>\n<td headers=\"stat_4\" class=\"gt_row gt_center\"></td>\n<td headers=\"stat_5\" class=\"gt_row gt_center\"></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-style: italic;\">    Asian</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">0.5%</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">0.4%</td>\n<td headers=\"stat_3\" class=\"gt_row gt_center\">0.4%</td>\n<td headers=\"stat_4\" class=\"gt_row gt_center\">0.5%</td>\n<td headers=\"stat_5\" class=\"gt_row gt_center\">0.4%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-style: italic;\">    Black</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">16%</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">15%</td>\n<td headers=\"stat_3\" class=\"gt_row gt_center\">15%</td>\n<td headers=\"stat_4\" class=\"gt_row gt_center\">14%</td>\n<td headers=\"stat_5\" class=\"gt_row gt_center\">12%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-style: italic;\">    Other/Mixed</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">17%</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">17%</td>\n<td headers=\"stat_3\" class=\"gt_row gt_center\">17%</td>\n<td headers=\"stat_4\" class=\"gt_row gt_center\">17%</td>\n<td headers=\"stat_5\" class=\"gt_row gt_center\">16%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-style: italic;\">    White</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">66%</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">67%</td>\n<td headers=\"stat_3\" class=\"gt_row gt_center\">67%</td>\n<td headers=\"stat_4\" class=\"gt_row gt_center\">68%</td>\n<td headers=\"stat_5\" class=\"gt_row gt_center\">72%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Hispanic</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">21%</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">20%</td>\n<td headers=\"stat_3\" class=\"gt_row gt_center\">20%</td>\n<td headers=\"stat_4\" class=\"gt_row gt_center\">20%</td>\n<td headers=\"stat_5\" class=\"gt_row gt_center\">21%</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\" style=\"font-weight: bold;\">Weight</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">83 (24) )</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">94 (28) )</td>\n<td headers=\"stat_3\" class=\"gt_row gt_center\">109 (49) )</td>\n<td headers=\"stat_4\" class=\"gt_row gt_center\">123 (38) )</td>\n<td headers=\"stat_5\" class=\"gt_row gt_center\">139 (111) )</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"6\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span> %; Mean (SD) )</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n:::\n\n:::\n\n## Results\n\n::: panel-tabset\n### Build Model {.tabset .tabset-fade .tabset-pills}\n\n::: blue\nThe code snippet below tells R to conduct a multiple regression analysis by subtracting each participant's height at T1 from their height at T0. Relevant summary statistics are also provided.\n\n**Compute Multiple Regression Model**\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .fold-hide .cell-code}\n# Split data using the correct eventname values\nbaseline_data <- df %>% \n  filter(eventname == \"baseline_year_1_arm_1\") %>% \n  select(src_subject_id, Height_baseline = anthroheightcalc, Weight_baseline = anthroweightcalc)\n\nfollowup_data <- df %>% \n  filter(eventname == \"1_year_follow_up_y_arm_1\") %>% \n  select(src_subject_id, Height_followup = anthroheightcalc)\n\n# Merge baseline and follow-up data\nmerged_data <- baseline_data %>%\n  left_join(followup_data, by = \"src_subject_id\")\n\n# Check the first few rows of the merged data\n#head(merged_data)\n\n# Fit the regression model excluding NA values\nmodel <- lm(Height_followup ~ Height_baseline + Weight_baseline, data = merged_data, na.action = na.exclude)\n```\n:::\n\n\n:::\n\n### Model Summary {.tabset .tabset-fade .tabset-pills}\n\n::: blue\n\nA plot to show xxxxx.\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmodel_summary <- summary(model)\nprint(model_summary)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Height_followup ~ Height_baseline + Weight_baseline, \n    data = merged_data, na.action = na.exclude)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-53.49  -0.83  -0.09   0.74  65.88 \n\nCoefficients:\n                Estimate Std. Error t value Pr(>|t|)    \n(Intercept)     17.18159    0.41712    41.2   <2e-16 ***\nHeight_baseline  0.68665    0.00847    81.0   <2e-16 ***\nWeight_baseline  0.03026    0.00120    25.3   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2.38 on 11130 degrees of freedom\n  (735 observations deleted due to missingness)\nMultiple R-squared:  0.575,\tAdjusted R-squared:  0.575 \nF-statistic: 7.54e+03 on 2 and 11130 DF,  p-value: <2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\npar(mfrow = c(2, 2))  # Set up a 2x2 plotting area\nplot(model)  # Generate diagnostic plots\n```\n\n::: {.cell-output-display}\n![](2_Examples_ResidualizedChangeScores_files/figure-html/model-checking-1.png){fig-align='center' width=75%}\n:::\n:::\n\n\nThis regression analysis evaluates how baseline height and weight predict children's height at a 1-year follow-up. The output from our model provides several key statistics:\n\ni. an F-statistic of 7539.2168865;\nii. degrees of freedom of 11130;\niii. parameter estimates for baseline height and weight;\niv. standard errors for these estimates; and\nv. p-values for the significance of these estimates.\n\nFor every one unit increase in baseline height, there's an associated increase of approximately 0.687 units in the follow-up height, and this effect was statistically significant with a p-value of 0. Similarly, for every one unit increase in baseline weight, there's an associated increase of approximately 0.0303 units in the follow-up height, which is also statistically significant with a p-value of 3.9902186\\times 10^{-137}. Overall, this model explains a substantial portion of the variance in follow-up height, with an adjusted R-squared value of 0.5753. The overall model is highly significant with a p-value less than 0, indicating that the predictors, collectively, have a significant relationship with the dependent variable.\n\n:::\n\n### Model Plots  {.tabset .tabset-fade .tabset-pills}\n\n::: blue\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Scatterplot with regression line for Weight_baseline\nggplot(merged_data, aes(x = Weight_baseline, y = Height_followup)) +\n  geom_point(alpha = 0.5) +\n  geom_smooth(method = \"lm\", color = \"black\") + \n  labs(title = \"Relationship between Baseline Weight and Follow-up Height\",\n       x = \"Baseline Weight\",\n       y = \"Follow-up Height\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](2_Examples_ResidualizedChangeScores_files/figure-html/scatterplot-1.png){fig-align='center' width=75%}\n:::\n:::\n\n\nThe scatterplot visually depicts the relationship between children's weights at baseline (Weight_baseline) and their heights at Year_1 (Height_followup). Each point on the plot represents a child, with their baseline weight plotted on the x-axis and their Year_1 height on the y-axis. The clear positive linear trend, as illustrated by the black regression line, indicates that children who had higher weights at baseline generally had higher heights at Year_1. While further statistical analyses can quantify the strength and direction of this relationship, visually, the data suggests a pronounced positive association between baseline weight and follow-up height.\n\n:::\n:::\n\n## Wrapping Up\n<div class = \"blue\">\n\n::: panel-tabset\n### Write-up {.tabset .tabset-fade .tabset-pills}\n\n::: blue\n\nThe regression analysis was conducted to predict children's height at the 1-Year follow-up using their baseline height (Height_baseline) and weight (Weight_baseline). Both predictors were statistically significant. Specifically, for every one-unit increase in baseline height, the height at Year_1 increased by approximately 0.687 units, while holding weight constant. Similarly, for every one-unit increase in baseline weight, the height at Year_1 increased by about 0.0303 units, while holding baseline height constant. The overall model explained a substantial 57.53% of the variance in height at the 1-Year follow-up, as indicated by the adjusted R-squared value.\n  \n\n:::\n:::",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}